accounts/urls.py
from django.urls import path
from.import views
from django.contrib.auth import views as p_views


urlpatterns=[
	path('signup/',views.signup_view,name="signup"),
	path('login/',views.login_view,name="login"),
	path('logout/',views.logout_view,name="logout"),
	path('password-change/',p_views.PasswordChangeView.as_view(),name='password_change'),
	path('password-change/done/',p_views.PasswordChangeDoneView.as_view(),name='password_change_done'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path
from.import views

urlpatterns = [
    path('',views.article_list,name="article_list"),
    path('create/',views.article_create,name="create"),
    path('<slug:slug>/',views.article_detail,name="detail"),
    path('<slug:slug>/like/',views.ArticleLikeToggle.as_view(),name="like-toggle"),
    path('<slug:slug>/api-like/',views.ArticleLikeAPIToggle.as_view(),name="like-api-toggle"),
]

djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from.import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('opportunity/',include('articles.urls')),
    path('',views.homepage,name='home'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('accounts/',include('accounts.urls')),
    path('', include('social_django.urls', namespace='social')),
]   
urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
class Article(models.Model):
	"""docstring for Article"""
	title  = models.CharField(max_length=100)
	slug   = models.SlugField()
	body   = models.TextField()
	date   = models.DateTimeField(auto_now_add=True)
	thumb  = models.FileField(blank=True)
	url    = models.CharField(max_length=255,null=True, blank=True)
	author = models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)
	likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True ,related_name='article_likes')

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:150] + '.....' 
	def get_absolute_url(self):
		return reverse('detail',kwargs={"slug": self.slug})
	def get_like_url(self):
		return reverse('like-toggle', kwargs={"slug": self.slug})
	def get_api_like_url(self):
		return reverse('like-api-toggle', kwargs={"slug": self.slug})

class Comment(models.Model):
	article = models.ForeignKey(Article,on_delete=models.CASCADE, related_name='comments')
	name = models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE,related_name='comments_creator')
	body = models.TextField()
	reply = models.ForeignKey('Comment', null = True , on_delete=models.CASCADE , related_name= 'replies')
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=True)
	class Meta:
		ordering = ('created',)
	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.article)

articles/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from.import models
from .models import Comment
class CreateArticle(forms.ModelForm):
	class Meta:
		model=models.Article
		fields=['title','body','slug','thumb','url']

class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ['body']
		labels = {
		'body': _('Comment here')
		}
		widgets = {
            'body': forms.TextInput(attrs={'placeholder': 'Add a comment'}),
        }

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
def signup_view(request):
	if request.method=='POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user=form.save()
			login(request, user, backend='django.contrib.auth.backends.ModelBackend')
			return redirect('home')
	else:
		form = UserCreationForm()
	return render(request,'signup.html',{'form':form})

def login_view(request):
	if request.method=='POST':
		form = AuthenticationForm(data=request.POST)
		if form.is_valid():
			user = form.get_user()
			login(request,user)
			if 'next' in request.POST:
				return redirect(request.POST.get('next'))
			else:
				return redirect('home')
	else:
		form=AuthenticationForm()
	return render(request,"login.html",{'form':form})

def logout_view(request):
	if request.method=="POST":
		logout(request)
		return redirect("home")

articles/views.py
from django.shortcuts import render,redirect
from .models import Article, Comment
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.views.generic import RedirectView
from.import forms
from .forms import CommentForm
def article_list(request):
	articles = Article.objects.all().order_by('-date')
	return render(request,'article_list.html',{'articles':articles})
def article_detail(request, slug):
	article = Article.objects.get(slug=slug)
	comments = article.comments.filter(active=True, reply=None)
	if request.method == 'POST':
		comment_form =CommentForm(data=request.POST)
		if comment_form.is_valid():
			new_comment = comment_form.save(commit=False)
			new_comment.article = article
			new_comment.name = request.user
			new_comment.reply_id = request.POST.get('comment_id')
			new_comment.comment_qs = None
			if new_comment.reply_id:
				new_comment.comment_qs = Comment.objects.get(id=new_comment.reply_id)
			new_comment.save()
			comment_form = CommentForm()
	else:
		comment_form = CommentForm()
	return render(request,'article_detail.html',{'article':article, 'comments':comments, 'comment_form':comment_form})
@login_required(login_url="/accounts/login/")
def article_create(request):
	if request.method=='POST':
		form=forms.CreateArticle(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.author = request.user
			instance.save()
			return redirect('home')
	else:
		form=forms.CreateArticle()
	return render(request,"article_create.html",{'form':form})

class ArticleLikeToggle(RedirectView):
	def get_redirect_url(self, *args, **kwargs):
		slug = self.kwargs.get("slug")
		obj = Article.objects.get(slug=slug)
		url_=obj.get_absolute_url()
		user = self.request.user
		if user.is_authenticated:
			if user in obj.likes.all():
				obj.likes.remove(user)
			else:
				obj.likes.add(user)
		return url_ 
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import authentication, permissions
from django.contrib.auth.models import User

class ArticleLikeAPIToggle(APIView):
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, slug=None, format=None):
        # slug = self.kwargs.get("slug")
        obj = Article.objects.get(slug=slug)
        url_ = obj.get_absolute_url()
        user = self.request.user
        updated = False
        liked = False
        if user.is_authenticated:
            if user in obj.likes.all():
                liked = False
                obj.likes.remove(user)
            else:
                liked = True
                obj.likes.add(user)
            updated = True
        data = {
            "updated": updated,
            "liked": liked
        }
        return Response(data)

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render
from articles.models import Article
def homepage(request,template='path/to/templates'):
	context = {
	    'articles': Article.objects.all().order_by('-date'),
    }
	#return HttpResponse('homepage')
	return render(request,'homepage.html',context)
def about(request):
	#return HttpResponse('about')
	return render(request,'about.html')
def contact(request):
	return render(request,'contact.html')

accounts/templates/login.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Login</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<style>
body {
  font-family: "Open Sans", sans-serif;
  height: 100vh;
  background: linear-gradient(rgba(82, 96, 174, 0.7), rgba(8, 17, 27, 0.7)), url("/static/images/hero-bg.jpg") 50% fixed;
  background-size: cover;

}
* {
  box-sizing: border-box;
}

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column;
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 15px;
 
}

.login {
  border-radius: 6px 6px 7px 7px;
  padding: 10px 20px 20px 20px;
  width: 90%;
  max-width: 320px;
  background: #ffffff;
  position: relative;
  padding-bottom: 80px;
  box-shadow: 0px 1px 5px rgba(0, 0, 0, 0.3);
}
.login1 {
  border-radius: 6px 6px 7px 7px;
  padding: 30px 0px 0px 0px;
  width: 90%;
  max-width: 320px;
  position: relative;
  text-align: center;
}
.login.loading button {
  max-height: 100%;
  padding-top: 50px;
}
.login.loading button .spinner {
  opacity: 1;
  top: 40%;
}
.login.ok button {
  background-color: #8bc34a;
}
.login.ok button .spinner {
  border-radius: 0;
  border-top-color: transparent;
  border-right-color: transparent;
  height: 20px;
  animation: none;
  transform: rotateZ(-45deg);
}
.login input {
  display: block;
  padding: 15px 20px;
  margin-bottom: 15px;
  width: 100%;
  border: 1px solid #d40ff2;
  transition: border-width 0.2s ease;
  border-radius: 25px;
  color: #ccc;
  margin-top: 5px;
}
.login input + i.fa {
  color: #fff;
  font-size: 1em;
  position: absolute;
  margin-top: -47px;
  opacity: 0;
  left: 0;
  transition: all 0.1s ease-in;
}
.login input:focus {
  outline: none;
  color: #444;
  border-color: #2196F3;
  border-left-width: 35px;
}
.login input:focus + i.fa {
  opacity: 1;
  left: 30px;
  transition: all 0.25s ease-out;
}
.login a {
  font-size: 0.8em;
  color: #2196F3;
  text-decoration: none;
}
.login .title {
  color: #444;
  font-size: 1.2em;
  font-weight: bold;
  margin: 10px 0 30px 0;
  border-bottom: 1px solid #eee;
  padding-bottom: 20px;
}
.login label {
  color: #444;
  font-size: 1.0em;
  font-weight: bold;
  margin: 10px 0 30px 0;
  padding-bottom: 20px;
}
.login button {
  width: 100%;
  height: 100%;
  padding: 10px 10px;
  background: #2196F3;
  color: #fff;
  display: block;
  border: none;
  margin-top: 20px;
  position: absolute;
  left: 0;
  bottom: 0;
  max-height: 60px;
  border: 0px solid rgba(0, 0, 0, 0.1);
  border-radius: 0 0 6px 6px;
  transform: rotateZ(0deg);
  transition: all 0.1s ease-out;
  border-bottom-width: 7px;
  cursor: pointer;
}
.login:not(.loading) button:hover {
  box-shadow: 0px 1px 3px #2196F3;
}
.login:not(.loading) button:focus {
  border-bottom-width: 4px;
}
.hovicon {
    display: inline-block;
    font-size: 30px;
    line-height: 60px;
    cursor: pointer;
    margin: 10px;
    width: 60px;
    height: 60px;
    border-radius: 50%;
    text-align: center;
    position: relative;
    text-decoration: none;
    z-index: 1;
    color: #fff;
}

.hovicon:after {
    pointer-events: none;
    position: absolute;
    width: 100%;
    height: 100%;
    border-radius: 50%;
    content:'';
    -webkit-box-sizing: content-box;
    -moz-box-sizing: content-box;
    box-sizing: content-box;
}
.hovicon:before {
    speak: none;
    font-size: 48px;
    line-height: 90px;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    display: block;
    -webkit-font-smoothing: antialiased;
}

.hovicon.effect-1:after {
    top: -7px;
    left: -7px;
    padding: 7px;
    box-shadow: 0 0 0 4px #fff;
    -webkit-transition: -webkit-transform 0.2s, opacity 0.2s;
    -webkit-transform: scale(.8);
    -moz-transition: -moz-transform 0.2s, opacity 0.2s;
    -moz-transform: scale(.8);
    -ms-transform: scale(.8);
    transition: transform 0.2s, opacity 0.2s;
    transform: scale(.8);
    opacity: 0;
}
 .hovicon.effect-1.sub-a:hover {
    background: rgba(255, 255, 255, 1);
    color: #0084FF;
}
.hovicon.effect-1.sub-a:hover:after {
    -webkit-transform: scale(1);
    -moz-transform: scale(1);
    -ms-transform: scale(1);
    transform: scale(1);
    opacity: 1;
}
 .hovicon.effect-1.sub-b:hover {
    background: rgba(255, 255, 255, 1);
    color: #dd4b39;
}
.hovicon.effect-1.sub-b:hover:after {
    -webkit-transform: scale(1);
    -moz-transform: scale(1);
    -ms-transform: scale(1);
    transform: scale(1);
    opacity: 1;
}
.tooltip {
  position: relative;
  display: inline-block;
  padding-bottom: 5px;
}

.tooltip .tooltiptext {
  visibility: hidden;
width: 150px;
background-color: #fff;
color: #000;
text-align: center;
border-radius: 27px;
padding: 5px 5px;
position: absolute;
z-index: 0;
bottom: 150%;
left: 50%;
margin-left: -70px;
}

.tooltip .tooltiptext::after {
  content: "";
  position: absolute;
  top: 100%;
  left: 50%;
  margin-left: -5px;
  border-width: 5px;
  border-style: solid;
  border-color: white transparent transparent transparent;
}

.tooltip:hover .tooltiptext {
  visibility: visible;
}
</style>
<body>
<div class="wrapper">
<form class="login" action="/accounts/login/" method="POST">
	 <p class="title">Log in</p>
 		{% csrf_token %}
 		<label for="id_username">Username:</label>
    <input type="text" name="username" autofocus="" placeholder="Username" required="" id="id_username">
    <i class="fa fa-user"></i>
    <label for="id_password">Password:</label>
    <input type="password" name="password" placeholder="Password" required="" id="id_password">
    <i class="fa fa-key"></i>
 		{% if request.GET.next %}
 		<input type="hidden" name="next" value="{{request.GET.next}}">
 		{% endif %}
 		<button type="submit">
      <span class="state">Log in</span>
      </button>
 	</form>
   <div class="login1"><div class="tooltip"><b style="color: #ffffff;" >Other options for Login</b>
  <span class="tooltiptext">Google | Facebook</span>
</div><br>
<a href="{% url "social:begin" "google-oauth2" %}" class="hovicon effect-1 sub-b"><i class="fa fa-google"></i></a>
  <a href="{% url "social:begin" "facebook" %}" class="hovicon effect-1 sub-a"><i class="fa fa-facebook"></i></a>
 </div>
 </div>
</body>
</html>

articles/templates/article_create.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>Counseling</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- mobile specific metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- CSS
    ================================================== -->
    <link href='https://fonts.googleapis.com/css?family=Lato:400,100,300' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:200,400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <script src="https://use.fontawesome.com/20ab91acc4.js"></script>
     <link rel="shortcut icon" href="/static/images/favicon.png" type="image/x-icon">
    <link rel="icon" type="image/x-icon" href="/static/images/favicon.png">

    
</head>
<style>
  body {
  margin: 0;
  padding: 0;
  
}

#contact {
  width: 100%;
  height: auto;
  background: linear-gradient(rgba(15, 15, 17, 0.7), rgba(8, 17, 27, 0.7)), url("/static/images/hero-bg1.jpg") 50% fixed;
  background-size: cover;
  overflow: hidden;
  padding-bottom: 200px;
}
@import url(https://fonts.googleapis.com/css?family=Raleway);
.section-header {
  text-align: center;
  margin: 0 auto;
  padding-top: 50px;
  margin-bottom: 50px;
  font-family: 'Raleway';
  font: 300 60px ;
  letter-spacing: 6px;
  color: #fff;
  margin-bottom: 25px;
}

.contact-wrapper {
  margin: 0 auto;
  padding-top: 20px;
  position: relative;
  max-width: 800px;
}

/* Begin Left Contact Page */
.form-horizontal {
  max-width: 400px;
  font-family: 'Lato';
  font-weight: 400;
  margin-left: auto;
  margin-right: auto;
  float: left;
}

.form-control, textarea {
  width: 800px;
  background-color: #111;
  color: #fff;
  letter-spacing: 1px;
  height:40px;
    font-size:14pt;
}

.send-button {
  margin-top: 15px;
  height: 34px;
  width: 400px;
  overflow: hidden;
  transition: all .2s ease-in-out;
}

.button {
  width: 400px;
  height: 34px;
  transition: all .2s ease-in-out;
}

.send-text {
  display: block;
  margin-top: 10px;
  font: 300 14px 'Lato', sans-serif;
  letter-spacing: 2px;
}

.button:hover {
  transform: translate3d(0px, -29px, 0px);
}

/* Begin Right Contact Page */
.direct-contact-container {
  max-width: 400px;
  float: right;
  margin-top: 5px;
}

/* Location, Phone, Email Section */
.contact-list {
  list-style-type: none;
  margin-left: -30px;
  padding-right: 20px;
}

.list-item {
  line-height: 4;
  color: #aaa;
}

.contact-text {
  font: 300 18px 'Lato', sans-serif;
  letter-spacing: 1.9px;
  color: #bbb;
}

.place {
  margin-left: 62px;
}

.phone {
  margin-left: 56px;
}

.gmail {
  margin-left: 53px;
}

.contact-text a {
  color: #bbb;
  text-decoration: none;
  transition-duration: 0.2s;
}

.contact-text a:hover {
  color: #fff;
  text-decoration: none;
}


/* Social Media Icons */
.social-media-list {
  position: relative;
  font-size: 2.3rem;
  text-align: center;
  width: 100%;
}

.social-media-list li a {
  color: #fff;
}

.social-media-list li {
  position: relative; 
  top: 0;
  left: -20px;
  display: inline-block;
  height: 70px;
  width: 70px;
  margin: 10px auto;
  line-height: 70px;
  border-radius: 50%;
  color: #fff;
  background-color: rgb(27,27,27);
  cursor: pointer; 
  transition: all .2s ease-in-out;
}

.social-media-list li:after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  width: 70px;
  height: 70px;
  line-height: 70px;
  border-radius: 50%;
  opacity: 0;
  box-shadow: 0 0 0 1px #fff;
  transition: all .2s ease-in-out;
}

.social-media-list li:hover {
  background-color: #fff; 
}

.social-media-list li:hover:after {
  opacity: 1;  
  transform: scale(1.12);
  transition-timing-function: cubic-bezier(0.37,0.74,0.15,1.65);
}

.social-media-list li:hover a {
  color: #111;
}

.copyright {
  font: 200 14px 'Oswald', sans-serif;
  color: #555;
  letter-spacing: 1px;
  text-align: center;
}

hr {
  border-color: rgba(255,255,255,.8); ;
}

/* Begin Media Queries*/
@media screen and (max-width: 760px) {
    
  .section-header {
    font-size: 65px;
  }
  .direct-contact-container, .form-horizontal {
    float: none;
    margin: 10px auto;
  }  
  .direct-contact-container {
    margin-top: 60px;
    max-width: 300px;
  }    
  .social-media-list li {
    height: 60px;
    width: 60px;
    line-height: 60px;
  }
  .social-media-list li:after {
    width: 60px;
    height: 60px;
    line-height: 60px;
  }
}

@media screen and (max-width: 569px) {
  #contact {
    height: 800px;
    }
  .section-header{
    font-size: 50px;
  }
  .direct-contact-container, .form-wrapper {
    float: none;
    margin: 0 auto;
  }  
  .form-control, textarea {
    max-width: 340px;
    margin: 0 auto;
  }
  
  .name, .email, textarea {
    width: 280px;
  } 
  .direct-contact-container {
    margin-top: 60px;
    max-width: 280px;
  }  
  .social-media-list {
    left: 0;
  }
  .social-media-list li {
    height: 55px;
    width: 55px;
    line-height: 55px;
    font-size: 2rem;
  }
  .social-media-list li:after {
    width: 55px;
    height: 55px;
    line-height: 55px;
  }
  
}

@media screen and (max-width: 410px) {
  .send-button {
    width: 99%;
  }
}
</style>
<body>
  <section id="contact">
  
  <h1 class="section-header">New Post</h1>
  
  <div class="contact-wrapper">
    
      <!---------------- 

      CONTACT PAGE LEFT 
    
      -----------------> 
    
    <form class="form-horizontal" role="form" action="{% url 'create' %}" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <div class="col-sm-12">
          <input class="form-control" type="text" name="title" maxlength="100" required="" id="id_title" placeholder="Title">
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-12">
          <input class="form-control" type="text" name="slug" maxlength="50" required="" id="id_slug" value="" placeholder="Slug">
        </div>
      </div>

      <textarea class="form-control" name="body"  rows="10" required="" id="id_body" data-gramm="true" data-txt_gramm_id="73b46138-465f-52db-0e1f-52ca2352929e" data-gramm_id="73b46138-465f-52db-0e1f-52ca2352929e" spellcheck="false" data-gramm_editor="true" placeholder="Body" ></textarea>
      <br>
      <label style="float: left;color: #00f2ff;font-size: 19px;margin-right: 10px;" for="id_thumb">Select an image: </label><input type="file" name="thumb" id="id_thumb" placeholder="add image for article">
      <div class="form-group">
        <div class="col-sm-12">
          <input class="form-control" type="text" name="url" maxlength="255" required="" id="id_url" value="" placeholder="Url">
        </div>
      </div>
     <input class="btn btn-primary send-button" id="submit" type="submit" value="Post">

    </form>
    
  </div>
  
</section>  
  
<script>
  const titleInput = document.querySelector('input[name=title]');
  const slugInput = document.querySelector('input[name=slug]');
  const slugify = (val) =>{
    return val.toString().toLowerCase().trim()
    .replace(/&/g,'-and-')
    .replace(/[\s\W-]+/g,'-')
  };
  titleInput.addEventListener('keyup',(e) => {
    slugInput.setAttribute('value',slugify(
      titleInput.value));
  });
</script>
</body>
</html>